### ISSUE TITLE
Use symlinks in docs/ to configure redirects?

### ISSUE THREAD

**Issue by osresearch** [datarobot/mkdocs-redirects#13]
An alternate way to configure the redirections would be to use symlinks in the `docs/` directory. That way it would not require editing the `mkdocs.yaml` file for every redirect and might be an easier way to manage the files.

**Comment by ghost** [comment]
Personally, I'm not sure about this. I have many redirects configured at the moment (300+) and I prefer to have them explicitly configured on a centralized location. It also makes it easier to see the changes to the redirects in the git history.

**Comment by ktomk** [comment]
I'm using symbolic links to create the `docs/` (`docs_dir`) content as the repository file-layout is not inherently compatible with the `docs/` (`docs_dir`) base in Mkdocs. This works very well with Mkdocs and turning all those into redirects would not work.

So to answer your question raised with this issue:  No, do not use symlinks in `docs/` to configure redirects as they first of all work for the actual content which is incompatible with redirects.

To generalize: Such a change would break compatibility with Mkdocs. Symbolic links have a different meaning for Mkdocs already, it is not possible to use them as redirects *as well*.

Please let me know if you think this is an over-generalization.

**Comment by pawamoy** [comment]
@ktomk made a good point, and even without considering backward-compatibility with MkDocs, symlinks have all kinds of quirks that would make such a feature unreliable IMO. I'll close this :slightly_smiling_face:

**Comment by ktomk** [comment]
> Symbolic links make the Unix file system non-hierarchical, resulting in multiple valid path names for a given file. This ambiguity is a source of confusion, especially since some shells work overtime to present a consistent view from programs such as pwd, while other programs and the kernel itself do nothing about the problem.

don't think it must become necessarily unreliable, but "quirks" reminded me of [this paper](https://9p.io/sys/doc/lexnames.html) @pawamoy 

btw. having all redirects in a catalog [as commented](https://github.com/mkdocs/mkdocs-redirects/issues/13#issuecomment-658241042) enhances the maintainability of a site in my practice (and this is not specifically mkdocs, but more general feedback).
