### ISSUE TITLE
Re-generate a mkdocs.yml file with redirects

### ISSUE THREAD

**Issue by leeyspaul** [datarobot/mkdocs-redirects#26]
I've got a small script going that will generate a new `mkdocs.yml` file from any `renamed` files in `git status`. It'd be nice to have a similar functionality with this plugin that will automatically add the redirects for me as it's quite a laborious process to add each individual change (especially for large changes) at once. 

Is this something we could look into? 

Thanks for the awesome plugin!

**Comment by pawamoy** [comment]
We could simply start by sharing this script here, and maybe include it in the docs. Would you like to share it? In the meantime I'll close this.
