### ISSUE TITLE
Missing LICENSE in PyPI sdist

### ISSUE THREAD

**Issue by manisandro** [datarobot/mkdocs-redirects#30]
The sdists on PyPI do not contain the LICENSE file. please add

    license_files=['LICENSE']

to setup.py to amend for this. In the meantime, could the 1.0.3 release be tagged on GitHub, so that the GitHub archive can be used instead?

**Comment by snoir** [comment]
I second this, it would be great to have the LICENSE file in sdist.

I was also wondering if it could be possible to include the `tests/` directory. I'm making a FreeBSD port for mkdocs-redirects and it's a nice thing to be able to launch the test suite from the ports framework.
If not possible or wanted, the port would rely on the Github repository, so the git tags will be required.

Thanks !
