### ISSUE TITLE
Handing over maintenance?

### ISSUE THREAD

**Issue by oprypin** [datarobot/mkdocs-redirects#32]
Do the current maintainers have any plans to continue working on this package (i.e. merging the pending fixes and releasing them)? If not, would you be open to handing over maintenance?

I'm the current maintainer of MkDocs itself, and I offer to maintain this package, including moving it to mkdocs organization if necessary.

@burkestar  @carsongee

Continuing from https://github.com/datarobot/mkdocs-redirects/issues/23#issuecomment-994097624

**Comment by burkestar** [comment]
Hi @oprypin - Thanks for your persistence :)

Sorry I've been neglecting this for awhile now and the developer on the team who was primarily maintaining it has moved on.

I would welcome your taking over maintenance of it, but will need to figure out our internal process for that.

We would need to transfer the Github repo to your org and also initiative a transfer of ownership for the PyPi package hosting.

There's also the possibility one of our internal teams could take this over and help get it updated.  I'll keep you posted.  Hopefully we can get this resolved next week.

Best,
Dustin

**Comment by oprypin** [comment]
Ah thanks!

And in case of a transfer, perhaps we should include some credits for DataRobot. I realize that there's no other prominent link back to it other than currently being part of that organization.

Such as this (green marker shows possible new addition to README)

![image](https://user-images.githubusercontent.com/371383/150201939-58bba55e-f94f-4ac0-9e58-5d6ebbbcbad2.png)

**Comment by oprypin** [comment]
Bump :smile:

**Comment by burkestar** [comment]
@oprypin I got approval for the transfer.  What are the next steps?  I can transfer the github repo and the PyPi package hosting.

**Comment by oprypin** [comment]
Thanks @burkestar 
So, you can do this:

* https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization
   Transfer it to "mkdocs". If that doesn't work, maybe instead you'll have to add me to owners of this repo

* Transfer on PyPI to https://pypi.org/user/oprypin/
  at https://pypi.org/manage/project/mkdocs-redirects/collaboration/

**Comment by burkestar** [comment]
I invited you to PyPI as an owner, and our Github org admins will transfer the repo soon.

Thanks!

**Comment by burkestar** [comment]
@oprypin It wouldn't let us transfer it to mkdocs org (we're not allowed to create public repos in the org) and we couldn't transfer it to your personal account since there's already a repo there of the same name.

@kobayashi69 transferred it to his personal account and invited you as collaborator.  

From there, you should be able to transfer it into the mkdocs org.

Otherwise, you'll just have to fork the repo and we'll have ours just say "moved, see here instead" with a link.

**Comment by oprypin** [comment]
Thanks! So, the PyPI part is fully done.

And the GitHub part - this plan sounds like it will work! I just accepted being a collaborator there. But I think @kobayashi69 will need to make me an owner of the repository. Because currently, I can't see the "Settings" tab (which is where the move would be performed) at all.

**Comment by kobayashi69** [comment]
Hello Oleh,

I'm trying to transfer it to you but it looks like because you have a copy
I can't.

[image: Screen Shot 2022-03-26 at 9.28.18 AM.png]

**Comment by oprypin** [comment]
Thanks.
Well, what I meant was just changing my status in the list of people inside this repository.
But, a direct transfer will work just as fine. I have deleted my copy of the repository, so it should work now.

**Comment by kobayashi69** [comment]
Initiated the transfer

**Comment by oprypin** [comment]
Nice! Everything worked well, even if it took 3 transfers :smile: 

* https://github.com/datarobot/mkdocs-redirects
* https://github.com/kobayashi69/mkdocs-redirects
* https://github.com/oprypin/mkdocs-redirects
* https://github.com/mkdocs/mkdocs-redirects

Now I'm just wondering - if either of us two created a fork of mkdocs-redirects, would that break this chain of redirects. For now I'll try to not make a fork in my profile if it can be avoided.

**Comment by nemchik** [comment]
> Nice! Everything worked well, even if it took 3 transfers 😄
> 
> * https://github.com/datarobot/mkdocs-redirects
> * https://github.com/kobayashi69/mkdocs-redirects
> * https://github.com/oprypin/mkdocs-redirects
> * https://github.com/mkdocs/mkdocs-redirects
> 
> Now I'm just wondering - if either of us two created a fork of mkdocs-redirects, would that break this chain of redirects. For now I'll try to not make a fork in my profile if it can be avoided.

Random stranger popping in to say: yes it will break the redirect chain if anyone in the chain makes a fork from the current repo. I haven't dealt with a multi-hop chain, so really I'd be most curious if someone in the middle (not the first or last) made a fork, but it's probably best to avoid it if everyone involved is wanting to keep the redirect chain.
