### ISSUE TITLE
html to html redirection

### ISSUE THREAD

**Issue by syntezzz1** [datarobot/mkdocs-redirects#38]
Hi!

I have a site `http://example-site1.com/example/error-description-1.html` created with mkdocs (example/error-description-1.md)

This site is accessed from Linux, which escapes symbols like this: `http:\/\/example-site1.com\/example\/error-description-1.html`

If you just copy this link and paste to a browser you will get this: `http://example-site1.com//example//error-description-1.html`

I need to create redirection from broken link  `http://example-site1.com//example//error-description-1.html` to correct link `http://example-site1.com/example/error-description-1.html`.

Can I do this with your plugin?

**Comment by chrisjonesonline** [comment]
Try creating (or updating) a file named .htaccess

This file should be placed within the base/root directory of each website.

Within this file, paste the following code, and replace the links with the correct path to each of your error pages.

```
ErrorDocument 400 http://example-site1.com/example/error-description-1.html
ErrorDocument 401 http://example-site1.com/example/error-description-2.html
ErrorDocument 403 http://example-site1.com/example/error-description-3.html
ErrorDocument 404 http://example-site1.com/example/error-description-4.html
ErrorDocument 500 http://example-site1.com/example/error-description-5.html
```

**Comment by chrisjonesonline** [comment]
Try creating (or updating) a file named **.htaccess**

This file should be placed within the **base/root** directory of each website.

Within this file, paste the following code, and replace the links with the correct path to each of your error pages.

```ErrorDocument 400 http://example-site1.com/example/error-description-1.html
ErrorDocument 401 http://example-site1.com/example/error-description-2.html
ErrorDocument 403 http://example-site1.com/example/error-description-3.html
ErrorDocument 404 http://example-site1.com/example/error-description-4.html
ErrorDocument 500 http://example-site1.com/example/error-description-5.html

**Comment by chrisjonesonline** [comment]
Try creating (or updating) a file named **.htaccess**

This file should be placed within the **base/root** directory of your website.

Within this file, paste the following code, and replace the links with the correct path to each of your error pages.

```
ErrorDocument 400 http://example-site1.com/example/error-description-1.html
ErrorDocument 401 http://example-site1.com/example/error-description-2.html
ErrorDocument 403 http://example-site1.com/example/error-description-3.html
ErrorDocument 404 http://example-site1.com/example/error-description-4.html
ErrorDocument 500 http://example-site1.com/example/error-description-5.html
