### ISSUE TITLE
When I redirect it tries to download the file

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [datarobot/mkdocs-redirects#52]
When I create a redirect from "aaanbbbcdsc" to "index.md" Firefox tries to download the file. What am I missing?

**Comment by pawamoy** [comment]
Unfortunately that's not enough information for us to help you. Do you still experience this issue? Could you provide a minimal reproducible example that demonstrates the issue you describe? In the meantime I will close as not planned :slightly_smiling_face:
