### ISSUE TITLE
please provide a wheelon PyPi

### ISSUE THREAD

**Issue by cburroughs** [datarobot/mkdocs-redirects#61]
Thanks for the plugin!  Could you please provide a wheel along with the tarball on PyPi?

**Comment by pawamoy** [comment]
@tomchristie I'm going to proceed and push a wheel (if PyPI allows me).

**Comment by pawamoy** [comment]
@cburroughs thanks for the heads up, it's done, see https://pypi.org/project/mkdocs-redirects/#files :slightly_smiling_face:
