### ISSUE TITLE
Document redirection link

### ISSUE THREAD

**Issue by dp1218** [datarobot/mkdocs-redirects#62]
The redirection may be broken if the javascript of the page cannot be executed because of a [middleware](https://backstage.io/docs/features/techdocs/) or if the browser of the client disabled it. Also note that the meta redirect is set as [deprecated by the W3C](https://www.w3.org/TR/WCAG10-HTML-TECHS/#meta-element).

With those conditions, the human may land on a page which is in fact a dead end because no information is provided to tell them what should have happened.

[This PR](https://github.com/mkdocs/mkdocs-redirects/pull/60) proposes a fix by printing a link to click to follow manually the redirection.

**Comment by pawamoy** [comment]
Thanks for the reminder @dp1218 :slightly_smiling_face: I have approved the PR and will merge it in a couple days.
