### ISSUE TITLE
Use status code "301 moved permanently" for redirects instead of "200 OK"

### ISSUE THREAD

**Issue by jakob-bagterp** [datarobot/mkdocs-redirects#70]
When working with redirects and SEO, Google prefers to have to get "301 moved permanently" status code instead of the current "200 OK" status code when using this plugin. Is that possible to change, or maybe it has implications?

**Comment by pawamoy** [comment]
I don't think it's possible. This plugin works by creating the old pages, and adding some code in them to redirect to the new ones. That means the old pages *exist*, and servers will send back HTTP 200. This is out of our control. If you have control over the server serving the static site, you can configure it to send back HTTP 301 for all your moved pages (and you'll probably have to stop using this plugin then).

**Comment by pawamoy** [comment]
Unless there's a standard way across web servers to configure 301 over 200 with the *file structure only* (or other features of *static sites*), this won't be possible, so I'll close for now. If *some* servers support that, we could consider supporting different output mode (one per supported server), but I won't have time to work on that myself.

**Comment by jakob-bagterp** [comment]
Okay, I understand the issue now: 301 and 302 redirects are a server-side operation, and while MkDocs generate static pages, that's no server involved other than serving a file to the requester.

Another approach: Would it be possible to add the `<meta http-equiv="refresh"  content="0; url=/new/url.html">` to the `<head>` element? Some claim [this approach could work](https://stackoverflow.com/a/19717455/13115170) and is accepted by Google now that the canonical link is already there.

**Comment by pawamoy** [comment]
> Okay, I understand the issue now: 301 and 302 redirects are a server-side operation, and while MkDocs generate static pages, that's no server involved other than serving a file to the requester.

Exactly (at least the first part): MkDocs only *builds* the files, then it's an entirely different piece of software that serves them, and they have no interactions whatsoever. MkDocs can't even know *which* server will be used (Apache, Nginx, etc.).

> Another approach: Would it be possible to add the `<meta http-equiv="refresh"  content="0; /new/url.html">` to the <head> element?

That's what we do already :relaxed:
https://github.com/mkdocs/mkdocs-redirects/blob/df6b0a8348b6cf25c405f93f0328eff7ae510121/mkdocs_redirects/plugin.py#L25
